### ISSUE TITLE
Help Building a MacOS App

### ISSUE THREAD

**Issue by captaindavepdx** [mayeaux/videodownloader#10]
Hi @mayeaux !

Your video downloader is awesome, thank you for sharing it with the GitHub community! =]

I'm trying to integrate your video downloader into a native MacOS app. The application is for internal use only, so it won't be sold or anything. And I was wondering if you'd be able to help troubleshoot it?  

David

**Comment by mayeaux** [comment]
Hey thanks, but there's already a native version of it available here: 
https://github.com/mayeaux/videodownloader/releases/download/1.0.0/videodownloader-1.0.0.dmg

That doesn't have the latest code, but basically Electron can be packaged as a native app for the different operating systems, that's one of the reasons I chose it. Let me know if that clears things up for you and thanks for the support!

**Comment by captaindavepdx** [comment]
Hi @mayeaux , thanks for getting back about this! To clarify, I'm trying to add your download feature into my own native MacOS app, which I'll use to download a list of video urls automatically. 

For example, this is an app that another awesome developer and I have been building from his repo, which downloads a complete website into a single html file. It's been a lot of fun, and we're almost done - just fixing a few bugs. Then, we're going to open source it, and post it in his community.

My Swift is ok, but I struggle with JavaScript. Would it be ok to reach out to you for help troubleshooting? =]

<img width="1280" alt="Screen Shot 2019-07-31 at 9 46 33 PM" src="https://user-images.githubusercontent.com/30560737/62266618-cffb2d80-b3dd-11e9-9011-f6efdfae1eb1.png">

**Comment by mayeaux** [comment]
My recommendation would be to use this as a project to improve your JavaScript. :) I'm already too stretched with projects but I wish you the best of luck! If you get super stuck with something feel free to reach out but I will leave this project to you, good luck!

**Comment by captaindavepdx** [comment]
Cool, thanks @mayeaux !

**Comment by mayeaux** [comment]
We can leave this issue open maybe someone else will read this thread and want to join you.

**Comment by captaindavepdx** [comment]
Sounds good, thanks @mayeaux ! =]

**Comment by captaindavepdx** [comment]
Hi @mayeaux !

I've been reviewing your code line-by-line, researching, and testing all day. And, I think I kind of get what's happening. But, just to make sure, could you please help clarify a few things?

It seemed like a lot of the code was for the user interface, as well as for formatting the data used to download videos. And, the heavy lifting was performed by the dependencies.

**Dependencies:**
`ffmpeg` was for converting the video from a data file to a video.
`fs` was for checking if a file exists and downloading files locally.
`youtube-dl` was for downloading videos from 110 sites.
`ytdl-core` was an alternative for downloading YouTube videos.

But, I don't understand how you're running an npm package in a native MacOS application. Does `electron` manage modules for you? And, did you rebuild the npm packages for `electron`?

**Comment by mayeaux** [comment]
Yeah sorry it's a bit jumbled, it was made very quickly. You're basically correct in all your assumption.

`ffmpeg` though is for post-processing with youtube-dl
`fs` is a native Node module
`ytdl-core` I think I use for getting titles. 

And Electron basically packages the apps in a way such that they can be accessed from the browser. I'm not totally sure how it works under the hood but it allows files from `node_modules` to be called from what feels like the client side.

Hope that helps! And yeah the code is pretty simple so might as well dive in yourself I figure, a good way to learn Javascript for sure.

**Comment by captaindavepdx** [comment]
Awesome, thanks @mayeaux ! =]

**Comment by captaindavepdx** [comment]
### @mayeaux , I figured it out!

Today, I went through your code again. I followed it from start to finish. I looked up and commented the purpose of each function. And, I finally realized that "youtube-dl" was an embedded executable file. And, that it was the key to downloading videos! =]

Then, I researched how to run an executable file in Swift, which turned out to be pretty simple.

And now, I just downloaded my first video in my MacOS application! Which, only really means that I setup "youtube-dl" and passed it a url in an arguments array. But, the important part is that it works!

Thank you @mayeaux , for your encouragement and clarification. Working through this project has definitely helped me understand JavaScript on a whole new level! =]

**Comment by mayeaux** [comment]
Hey perfect, glad to hear it man! Keep it up, knowing JavaScript will be really important in the coming years.
