### ISSUE TITLE
I download the video, it's just 51 minutes, but it's size is 12G

### ISSUE THREAD

**Issue by pathbox** [mayeaux/videodownloader#11]
Hi,  I download the video: https://www.youtube.com/watch?v=mC7nN8OShvY&list=PLMBAcjeGtKQbVUmhZrrPf4evOyrDgFOTX&index=9 ,

 it's just 51 minutes, but it's size is 12G, it is huge.

Is there a way that to choose a small size?

**Comment by mayeaux** [comment]
By default the app is downloading at the highest available bitrate. To select a lower quality you should go here:
https://github.com/mayeaux/videodownloader/blob/master/renderer.js#L94

And change that line to select the bitrate you want. Are you familiar with the youtube-dl API?

**Comment by pathbox** [comment]
@mayeaux  Ok  I got it.  Thanks a lot

**Comment by mayeaux** [comment]
Awesome, glad to hear. What was the code that you ended up using?
