### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by Unforgiven-wanda** [mayeaux/videodownloader#14]
Do you plan on releasing one?
Thank you.

**Comment by mayeaux** [comment]
Not really, I basically figure that if you're smart enough to use Linux you can just follow the steps to install it from source via NPM. Also I don't use Linux personally and can't really make an executable to target it (just an assumption but I feel pretty confident about that).

**Comment by Unforgiven-wanda** [comment]
Fair enough.
Have a good day.
