### ISSUE TITLE
Changing file format upon downloading

### ISSUE THREAD

**Issue by istumblebee** [mayeaux/videodownloader#19]
Any chance we can get a version of this that downloads in a .MP4 file format? .MKV is great, but Adobe Premiere is incompatible with .MKV files.

**Comment by mayeaux** [comment]
The way the logic is setup right now is to prioritize mp4 files, if you're receiving .MKV I believe it means there is no .mp4 file available, at which point converting to .mp4 is a bit outside the scope of this application. If enough people ask for it I imagine I could do it, what OS do you use?

**Comment by istumblebee** [comment]
Ah, then I'm not worried about it. Using Windows 10.

**Comment by mayeaux** [comment]
Yeah converting video is kind of opinionated and also very resource intensive, if enough people would ask for it I would do it otherwise I think it's a bit outside the scope of this application, thanks for the suggestion though! I'd recommend installing ffmpeg as a CLI and then using that.
