### ISSUE TITLE
Insecure string pickle

### ISSUE THREAD

**Issue by atrus05** [mayeaux/videodownloader#3]
When I try to download a video I get an error message saying "insecure string pickle". After some googling it seems to indicate that one of the reasons why this error message might pop up is if you are forgetting to close the stream that you're using for dumping the data structure. No idea if this is applicable for you though.

Video I tried to download in case that matters:
https://www.youtube.com/watch?v=-8XIR3OwKKo

The only value I changed in your GUI was the location to where it was being downloaded. And I changed it to a folder to which I have write rights.

No log seems to have been generated in the normal places (Mac OS X). Let me know where I can find them in case you are interested in what has been generated there.
I am using Mac OS X 10.14.1

**Comment by atrus05** [comment]
I updated to the latest Mac OS X Mojave, and I also noticed that I on this machine had a really old version of youtube-dl. After making those two changes, it now downloads videos. Closing this one.

**Comment by mayeaux** [comment]
Awesome glad to hear it.

**Comment by mayeaux** [comment]
It was probably the updating of OS X since the app itself calls an internal youtube-dl binary btw
