### ISSUE TITLE
resolution choice / arguments ?

### ISSUE THREAD

**Issue by nykoo** [mayeaux/videodownloader#9]
First of all thank you for this.

Is there a way to choose dl resolution (at least for youtube 360p, 720p or 1080p) ?

Regards

**Comment by mayeaux** [comment]
My pleasure hopefully you find it useful.

Currently it will just download the highest quality audio and video available, I will probably end up adding functionality whereby you can pass custom flags and then your functionality should be possible.

**Comment by nykoo** [comment]
Thank you very much for your answer :)
Your tool is great, even for a very code noob as i am. 
Thank you

**Comment by mayeaux** [comment]
Awesome to hear. Are you on Windows? 

Also if you go here:
https://github.com/mayeaux/videodownloader/blob/master/renderer.js#L48

You can pass different flags to youtube-dl and customize the arguments passed. Read up on how youtube-dl works and then you can use that to download custom resolutions

**Comment by nykoo** [comment]
Yes i'm on windows

i found the arguments but don't know how to insert it:
-f "best[height=720]
(Where idi i insret it ? did i remove the // in front of line ? )
anyway not a real problem, downloaded in max resolution and then re-convert it ;)

Thank you again for this tool and for your answers (and sorry for my bad english)

**Comment by mayeaux** [comment]
```
 // select download as audio or video
  if(downloadAsAudio){
    arguments.push('-f');

    // arguments.push('bestaudio');


    arguments.push('bestaudio[ext!=webm]');

    /** conversion taking too long atm **/
    // arguments.push('--extract-audio');
    //
    // arguments.push('--audio-format');
    //
    // arguments.push('mp3');

    // can add something here later
  }  else {

     arguments.push('-f');
     arguments.push('best[height=720]')
  }
```

No problem, add the part I just added in the else {} block and it should work! And your English is fine, happy to help and happy to hear it's working well on Windows :)

**Comment by nykoo** [comment]
Thank you for your so quick answer :)
But it don't work. i certainly did something wrong.
i insert the code in the else {} block of the renderer.js part but then i have an error:
`renderer.js:165 stderr: ERROR: requested format not available

renderer.js:165 stderr: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\YoutubeDL.py", line 1634, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available


renderer.js:182 child process exited with code 1`

The video is playable in 720 via youtube.

Anyway really not a problem i convert it to the size i needed and this is perfect.

Again thank you very much for your coding skills and you kindness.

**Comment by mayeaux** [comment]
Try to run `youtube-dl -F yoururl.com` to get the available formats. If you get `youtube-dl` working from the command line you should be able to test things manually before you plug it into videodownloader

**Comment by nykoo** [comment]
will try, thank you
